Module Module_Language
    Public Sub to_en()
        form_main.Text = "NetST (Network for Sequences and Traits)" + " ver. " + version
        form_main.文件FToolStripMenuItem.Text = "File"
        form_main.载入序列ToolStripMenuItem.Text = "Load Sequences"
        form_main.载入数据ToolStripMenuItem.Text = "Load Table"
        form_main.增加数据ToolStripMenuItem.Text = "Add Sequences"
        form_main.保存数据ToolStripMenuItem.Text = "Save Table"
        form_main.导出序列ToolStripMenuItem.Text = "Save Sequences"
        form_main.编辑ToolStripMenuItem.Text = "Edit"
        form_main.全选ToolStripMenuItem.Text = "Select All"
        form_main.清除ToolStripMenuItem.Text = "Clear"
        form_main.分析ToolStripMenuItem.Text = "Analyze"
        form_main.MSN单倍型网络ToolStripMenuItem.Text = "MSN Haplotype Network"
        form_main.MJN单倍型网络ToolStripMenuItem.Text = "MJN Haplotype Network"
        form_main.单倍型网络ToolStripMenuItem.Text = "TCS Haplotype Network"
        form_main.序列比对高速ToolStripMenuItem.Text = "Sequence Alignment (Mafft)"
        form_main.序列比对ToolStripMenuItem.Text = "Sequence Alignment (Muscle)"
        form_main.工具ToolStripMenuItem.Text = "Tools"
        form_main.清理序列ToolStripMenuItem.Text = "Clean Sequence Data"
        form_main.获取序列信息ToolStripMenuItem.Text = "Generate Sequence Table"
        form_main.日期转换数字ToolStripMenuItem.Text = "Date to Number Conversion"
        form_main.浏览ToolStripMenuItem.Text = "Browse"
        form_main.前进ToolStripMenuItem.Text = "Forward"
        form_main.后退ToolStripMenuItem.Text = "Backward"
        form_main.分析记录ToolStripMenuItem.Text = "View Records"
        form_main.EnglishToolStripMenuItem.Text = "中文"
        form_main.TabControl1.TabPages(0).Text = "Results"
        form_main.TabControl1.TabPages(1).Text = "Sequences"
        form_main.TabControl1.TabPages(2).Text = "Information"

        form_config_stand.Text = "Standardization"
        form_config_stand.CheckBox1.Text = "Use Unix line endings"
        form_config_stand.CheckBox2.Text = "Split names using:"
        form_config_stand.CheckBox6.Text = "Split names using:"
        form_config_stand.CheckBox7.Text = "Split names using:"
        form_config_stand.CheckBox8.Text = "Split names using:"
        form_config_stand.CheckBox9.Text = "Split names using:"
        form_config_stand.Label1.Text = "Use as the new name"
        form_config_stand.CheckBox5.Text = "Remove seq with ambiguous bases"
        form_config_stand.CheckBox3.Text = "Replace"
        form_config_stand.Label2.Text = "->"
        form_config_stand.CheckBox4.Text = "Use numbering as seq names"
        form_config_stand.Button1.Text = "OK"
        form_config_stand.Button2.Text = "Cancel"
        form_config_stand.Label3.Text = "Use as discrete trait"
        form_config_stand.Label5.Text = "Preview Names:"
        form_config_stand.Label4.Text = "Use as counts"
        form_config_stand.Label6.Text = "Use as continuous trait"
        form_config_stand.Label7.Text = "Split Results:"
        form_config_stand.Label8.Text = "Use as organism"


        form_config_clean.Text = "Clean"
        form_config_clean.CheckBox1.Text = "Use Unix line endings"
        form_config_clean.CheckBox2.Text = "Remove seq with ambiguous bases"
        form_config_clean.CheckBox3.Text = "Remove sew shorter than:"
        form_config_clean.CheckBox4.Text = "Remove seq with N percentage above:"
        form_config_clean.CheckBox5.Text = "Replace ambiguous bases with gap(-)"
        form_config_clean.CheckBox6.Text = "Replace in seq name:"
        form_config_clean.Button1.Text = "OK"
        form_config_clean.Button2.Text = "Cancel"
        form_config_clean.CheckBox7.Text = "Remove in sequence name:"
        form_config_clean.CheckBox8.Text = "Keep only seqs with the following in name:"
        form_config_clean.Label1.Text = "Input sequences:"
        form_config_clean.Label5.Text = "Preview Names:"
        form_config_clean.Label2.Text = "with"
        form_config_clean.Button3.Text = "Browse"



        form_config_clean.CheckBox1.Text = "Use Unix Line Endings"
        form_config_clean.CheckBox2.Text = "Remove Seqs Containing Ambiguous Bases"
        form_config_clean.CheckBox3.Text = "Remove Seqs Shorter than:"
        form_config_clean.CheckBox4.Text = "Remove Seqs with N Content Higher than:"
        form_config_clean.CheckBox5.Text = "Replace Ambiguous Bases with Gap(-)"
        form_config_clean.Button1.Text = "OK"
        form_config_clean.Button2.Text = "Cancel"
        form_config_clean.CheckBox7.Text = "Remove Seqs with Names Containing:"
        form_config_clean.CheckBox8.Text = "Keep Only Seqs with Names Containing:"
        form_config_clean.Label1.Text = "Input Sequences:"
        form_config_clean.Label2.Text = "with"
        form_config_clean.Label5.Text = "Name Preview:"
        form_config_clean.CheckBox6.Text = "Replace Characters in Seq Names"
        form_config_clean.Text = "Sequence Cleanup"

        language = "EN"

    End Sub

    Public Sub to_ch()
        form_main.Text = "NetST 序列和性状网络分析" + " ver. " + version
        form_main.文件FToolStripMenuItem.Text = "文件"
        form_main.载入序列ToolStripMenuItem.Text = "载入序列"
        form_main.载入数据ToolStripMenuItem.Text = "载入表格"
        form_main.增加数据ToolStripMenuItem.Text = "增加序列"
        form_main.保存数据ToolStripMenuItem.Text = "保存表格"
        form_main.导出序列ToolStripMenuItem.Text = "保存序列"
        form_main.编辑ToolStripMenuItem.Text = "编辑"
        form_main.全选ToolStripMenuItem.Text = "全选"
        form_main.清除ToolStripMenuItem.Text = "清除"
        form_main.分析ToolStripMenuItem.Text = "分析"
        form_main.MSN单倍型网络ToolStripMenuItem.Text = "MSN单倍型网络"
        form_main.MJN单倍型网络ToolStripMenuItem.Text = "MJN单倍型网络"
        form_main.单倍型网络ToolStripMenuItem.Text = "TCS单倍型网络"
        form_main.序列比对高速ToolStripMenuItem.Text = "序列比对(Mafft)"
        form_main.序列比对ToolStripMenuItem.Text = "序列比对(Muscle)"
        form_main.工具ToolStripMenuItem.Text = "工具"
        form_main.清理序列ToolStripMenuItem.Text = "清理序列数据"
        form_main.获取序列信息ToolStripMenuItem.Text = "序列生成表格"
        form_main.日期转换数字ToolStripMenuItem.Text = "日期转换数字"
        form_main.浏览ToolStripMenuItem.Text = "浏览"
        form_main.前进ToolStripMenuItem.Text = "前进"
        form_main.后退ToolStripMenuItem.Text = "后退"
        form_main.分析记录ToolStripMenuItem.Text = "查看记录"
        form_main.EnglishToolStripMenuItem.Text = "English"
        form_main.TabControl1.TabPages(0).Text = "结果"
        form_main.TabControl1.TabPages(1).Text = "序列"
        form_main.TabControl1.TabPages(2).Text = "信息"


        form_config_stand.Text = "序列标准化"
        form_config_stand.CheckBox1.Text = "使用Unix换行符"
        form_config_stand.CheckBox2.Text = "使用该分隔符拆分序列名"
        form_config_stand.CheckBox6.Text = "使用该分隔符拆分序列名"
        form_config_stand.CheckBox7.Text = "使用该分隔符拆分序列名"
        form_config_stand.CheckBox8.Text = "使用该分隔符拆分序列名"
        form_config_stand.CheckBox9.Text = "使用该分隔符拆分序列名"
        form_config_stand.Label1.Text = "将该位置作为新序列名"
        form_config_stand.CheckBox5.Text = "移除所有包含简并碱基的序列"
        form_config_stand.CheckBox3.Text = "替换序列名中"
        form_config_stand.Label2.Text = "为"
        form_config_stand.CheckBox4.Text = "使用编号作为序列的名称"
        form_config_stand.Button1.Text = "确定"
        form_config_stand.Button2.Text = "取消"
        form_config_stand.Label3.Text = "将该位置作为间断性状"
        form_config_stand.Label5.Text = "序列名预览:"
        form_config_stand.Label4.Text = "将该位置作为数量"
        form_config_stand.Label6.Text = "将该位置作为连续性状"
        form_config_stand.Label7.Text = "拆分结果预览:"
        form_config_stand.Label8.Text = "将该位置作为物种名"

        form_config_clean.Text = "清理序列"
        form_config_clean.CheckBox1.Text = "使用Unix换行符"
        form_config_clean.CheckBox2.Text = "移除所有包含简并碱基的序列"
        form_config_clean.CheckBox3.Text = "移除短于以下长度的序列"
        form_config_clean.CheckBox4.Text = "移除含N高于以下百分比的序列"
        form_config_clean.CheckBox5.Text = "将简并碱基替换为gap(-)"
        form_config_clean.CheckBox6.Text = "替换序列名中的字符"
        form_config_clean.CheckBox7.Text = "移除序列名包含以下字符的序列"
        form_config_clean.CheckBox8.Text = "只保留序列名包含以下字符的序列"
        form_config_clean.Label1.Text = "待处理序列:"
        form_config_clean.Label5.Text = "第一条序列名预览:"
        form_config_clean.Button1.Text = "确定"
        form_config_clean.Button2.Text = "取消"
        form_config_clean.Button3.Text = "浏览"


        form_config_clean.CheckBox1.Text = "使用Unix换行符"
        form_config_clean.CheckBox2.Text = "移除所有包含简并碱基的序列"
        form_config_clean.CheckBox3.Text = "移除短于以下长度的序列"
        form_config_clean.CheckBox4.Text = "移除含N高于以下百分比的序列"
        form_config_clean.CheckBox5.Text = "将简并碱基替换为gap(-)"
        form_config_clean.Button1.Text = "确定"
        form_config_clean.Button2.Text = "取消"
        form_config_clean.CheckBox7.Text = "移除序列名包含以下字符的序列"
        form_config_clean.CheckBox8.Text = "只保留序列名包含以下字符的序列"
        form_config_clean.Label1.Text = "待处理序列:"
        form_config_clean.Label2.Text = "替换为"
        form_config_clean.Label5.Text = "序列名预览:"
        form_config_clean.CheckBox6.Text = "替换序列名中的字符"
        form_config_clean.Text = "序列清理"

        language = "CH"


    End Sub
End Module
